### Add a new dog
POST http://localhost:8080/dogs
Content-Type: application/json

{
  "id": 1,
  "name": "Bobby",
  "gender": "Male",
  "weight": 10.0,
  "specialNotes": "Good dog",
  "dateOfArrival": "2025-04-18",
  "availableForAdoption": true,
  "roomNumber": 1,
  "colorId": 0,
  "furTypeId": 0,
  "sizeId": 0,
  "breedId": 0,
  "assignedEmployeeId": 0
}
